---
- hosts: openvswitch
  vars_files:
    - config/main.yaml
  tasks:
    - name: Ensure epel-release is installed
      yum:
        name: epel-release
        state: latest
    - name: Create a templorary folder
      file:
        path: /root/rpmbuild/SOURCES
        state: directory
    - name: Install dependencies
      yum:
        name: [wget, openssl-devel,  python-sphinx, python-six, gcc, make, python-devel, openssl-devel, kernel-devel, graphviz ,kernel-debug-devel, autoconf, automake, rpm-build, redhat-rpm-config, libtool, python-twisted-core, python-zope-interface, PyQt4, desktop-file-utils, libcap-ng-devel, groff, checkpolicy, selinux-policy-devel]
    - name: Download source files for OpenVSwitch
      get_url:
        url: http://openvswitch.org/releases/openvswitch-2.9.2.tar.gz
        dest: /root/rpmbuild/SOURCES
    - name: Unarchive sources
      unarchive:
        src: /root/rpmbuild/SOURCES/openvswitch-2.9.2.tar.gz
        dest: /root/rpmbuild/SOURCES
        remote_src: yes
    - name: Build sources with RPMBuild
      command: rpmbuild -bb --nocheck /root/rpmbuild/SOURCES/openvswitch-2.9.2/rhel/openvswitch-fedora.spec
    - name: Install package
      yum:
        name: /root/rpmbuild/RPMS/x86_64/openvswitch-2.9.2-1.el7.x86_64.rpm
        state: present
    - name: Run OpenVSwitch and make in autorunning
      service:
        name: openvswitch
        state: restarted
        enabled: yes
    - name: Create first bridge
      command: ovs-vsctl add-br ovsbridge0
      ignore_errors: yes
    - name: Deploy network-script template for OVS bridge
      template:
        src: templates/ifcfg-ovsbridge0
        dest: /etc/sysconfig/network-scripts/ifcfg-ovsbridge0
    - name: Deploy an extra management interface and connect it to OVS Bridge
      template:
        src: templates/ifcfg-mgmt0
        dest: /etc/sysconfig/network-scripts/ifcfg-mgmt0
    - name: Deploy an route establish script at start-up
      template:
        src: templates/route-ovsbridge0
        dest: /etc/sysconfig/network-scripts/route-ovsbridge0
    - name: Flush BOOTPROTO Parameter
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{item}}"
        line: "BOOTPROTO=none"
        regexp: "^BOOTPROTO.*"
      with_items:
        - "{{ OVS_PORTS }}"
    - name: Flush IP addresses from physical interfaces
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{item}}"
        state: absent
        regexp: "^IPADDR.*"
      with_items:
        - "{{ OVS_PORTS }}"
    - name: Add physical interfaces to OVS bridge
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{item[0]}}"
        line: "{{item[1]}}"
        state: present
      with_nested:
        - "{{ OVS_PORTS }}"
        - ["TYPE=OVSPort","DEVICETYPE=ovs","OVS_BRIDGE=ovsbridge0"]
    - name: Restarted network service
      service:
        name: network
        state: restarted
