---
- hosts: suricata
  vars_files:
    - config/main.yaml
  tasks:
  - name: Ensure epel-release is installed
    yum:
      name: epel-release
      state: latest
  - name: Install dependencies
    yum:
      name: [ jq, cargo, openssl-devel, PyYAML, lz4-devel, gcc, libpcap-devel, pcre-devel, libyaml-devel, file-devel, zlib-devel, jansson-devel, nss-devel ,libcap-ng-devel, libnet-devel ,tar, make, libnetfilter_queue-devel, lua-devel,wget]
  - name: Create a temporary folder
    file:
      path: "{{SURICATA_DEFAULT_SAVE_PATH}}"
      state: directory
  - name: Clone Suricata archive
    get_url:
      url: "https://www.openinfosecfoundation.org/download/{{SURICATA_VERSION}}.tar.gz"
      dest: "{{SURICATA_DEFAULT_SAVE_PATH}}/suricata-4.1.3.tar.gz"
  - unarchive:
      src: "{{SURICATA_DEFAULT_SAVE_PATH}}/suricata-4.1.3.tar.gz"
      remote_src: yes
      dest: /tmp/suricata
  - name: Configure installation
    command: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}/configure --libdir=/usr/lib64 --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-nfqueue --enable-lua"
    ignore_errors: yes
  - name: Make Suricata
    make:
      chdir: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}"
  - name: Install Requirements for Suricata Updater via pip
    pip:
      requirements: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}/suricata-update/requirements.txt"
  - name: Make Suricata update tools
    make:
      chdir: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}/suricata-update"
  - name: Install Suricata Update tool
    make:
      chdir: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}/suricata-update"
      target:  install
  - name: Add a symbolic link for Suricata executible for compatibility
    file:
      src: /usr/local/bin/suricata-update
      dest: /usr/bin/suricata-update
      state: link
  - name: Install Suricata, Set Configuration and Update rules
    make:
      chdir: "{{SURICATA_DEFAULT_SAVE_PATH}}/{{SURICATA_VERSION}}"
      target:  install-full
