- hosts: ipsec
  tasks:
    - name: Include Variables
      include_vars:
        dir: ../config
        extensions:
          - yaml
    - name: Apply strongswan VPN Connections configuration (swanctl used)
      template:
        src: "../templates/vpn.conf.j2"
        dest: "{{ IPSEC_CONF_PATH }}/vpn.conf"
    - name: Apply EAP-RADIUS configuration (charon used)
      template:
        src: ../templates/eap-radius.conf.j2
        dest:  /etc/strongswan/strongswan.d/charon/eap-radius.conf
    - name: Set Phase 2 for EAP-TTLS to be RADIUS
      lineinfile:
        path: /etc/strongswan/strongswan.d/charon/eap-ttls.conf
        regexp: '# phase2_method'
        line: "phase2_method = radius"
    - name: Set Preferred EAP methods for EAP-DYNAMIC module
      lineinfile:
        path: /etc/strongswan/strongswan.d/charon/eap-dynamic.conf
        regexp: '# preferred'
        line: "preferred = eap-tls"    
    - name: Run swanctl to apply configuration
      service:
        name: strongswan-swanctl
        state: restarted
        enabled: yes
