---
- hosts: elk
  vars_files:
    - config/main.yaml
  tasks:
  - name: Ensure epel-release is installed
    yum:
      name: epel-release
      state: latest
  - name: Install Java
    yum:
      name: java-1.8.0
      state: latest
  - name: Import GPG key for ElasticSearch repository
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - name: Deploy the repo template
    template:
      src: templates/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
  - name: Install ELK stack
    yum:
      name: [elasticsearch, logstash, kibana, filebeat, metricbeat]
      state: latest
  - name: Install nginx to work as a proxy server
    yum:
      name: nginx
      state: latest
  - name: Deploy nginx configuration to pass requests to Kibana
    template:
      src: templates/nginx.conf
      dest: /etc/nginx/conf.d/kibana.conf
  - name: Start nginx
    service:
      name: nginx
      enabled: yes
      state: started
  - name: Copy configuration files for Logstash
    template:
      src: "templates/logstash/{{item}}"
      dest: /etc/logstash/conf.d/"{{item}}"
    with_items:
      - 02-beats-input.conf
      - 10-syslog-filter.conf
      - 30-elasticsearch-output.conf
  - name: Make Elasticsearch listen on all interfaces
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      line: "{{item}}"
    with_items:
      - "network.bind_host: 0.0.0.0"
      - "node.master: true"
      - "node.data: true"
      - "transport.host: localhost"
      - "transport.tcp.port: 9300"
  - name: Enable System logs collection
    command: filebeat modules enable system
  - name: Allow  local proxies connection in SELinux
    command: setsebool httpd_can_network_connect 1 -P
    ignore_errors: yes
  - name: Allow connection through network to HTTP WebGUI
    firewalld:
      service: http
      permanent: yes
      state: enabled
  - name: Allow connection through firewalld to ELK stack
    firewalld:
      port: "{{item}}"
      permanent: yes
      state: enabled
    with_items:
      - 9300/tcp
      - 9200/tcp
      - 514/tcp
      - 514/udp
      - 5044/tcp
  - name: Start ELK and make in autorunning
    service:
      name: "{{item}}"
      enabled: yes
      state: started
    with_items:
      - elasticsearch
      - kibana
      - logstash
      - filebeat
      - metricbeat
