---
- hosts: target
  vars_files:
    - config/main.yaml
  tasks:
  - name: Ensure epel-release is installed
    yum:
      name: epel-release
      state: latest
  - name: Install Java
    yum:
      name: java-1.8.0
      state: latest
  - name: Import GPG key for ElasticSearch repository
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - name: Deploy the repo template
    template:
      src: templates/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
  - name: Install Filebeat and Metricbeat
    yum:
      name: [ filebeat, metricbeat]
      state: latest
  - name: Start Filebeat and Metricbeat and make it autorunning
    service:
      name: "{{item}}"
      enabled: yes
      state: started
    with_items:
      - filebeat
      - metricbeat
  - name: Deploy Filebeat configuration
    template:
      src: templates/filebeat/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
  - name: Deploy Metricbeat configuration
    template:
      src: templates/metricbeat/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: Setup Metricbeat and enable Elasticsearch and Kibana dashboards, visualizations and indexes
    command: "metricbeat modules enable {{item}}"
    with_items:
      - "{{METRICBEAT_ENABLED_MODULES}}"
  - name: Setup File and enable Elasticsearch and Kibana dashboards, visualizations and indexes
    command: "filebeat modules enable {{item}}"
    with_items:
      - "{{FILEBEAT_ENABLED_MODULES}}"
  - name: Setup modules for Filebeat
    command: filebeat setup
  - name: Setup modules for Metricbeat
    command: metricbeat setup
  - name: Restart services
    service:
      name: "{{item}}"
      state: restarted
    with_items:
      - filebeat
      - metricbeat
