- hosts: ipsec
  tasks:
    - name: Include Variables
      include_vars:
        dir: ../config
        extensions:
          - yaml
    - name: Initialize CA
      import_tasks: ../tasks/server_tasks.yaml
