- hosts: ca
  tasks:
    - name: Include Variables
      include_vars:
        dir: ../config
        extensions:
          - yaml
    - name: Initialize CA
      import_tasks: ../tasks/ca_tasks.yaml
