Vagrant.configure("2") do |config|


  config.vm.define "right" do |right|
    
    right.vm.box = "centos/7"
    right.vm.hostname = "right.local"
    right.vm.network "private_network" ,  ip:"192.168.50.10"
    right.vm.network "private_network" ,  ip:"10.11.13.10", netmask:"255.255.255.0",virtualbox__intnet: "net2" , auto_config: true

    right.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbooks/do_rightside.yml"
    end

  end


  config.vm.define "left" do |left|
    
    left.vm.box = "centos/7"
    left.vm.hostname = "leftside.local"
    left.vm.network "private_network" ,  ip:"192.168.50.20"
    left.vm.network "private_network" , ip:"10.11.12.10", netmask:"255.255.255.0",  virtualbox__intnet: "net2"

    left.vm.provision "ansible" do |ansible|
       ansible.playbook = "ansible/playbooks/do_leftside.yml"
    end

    left.vm.provision "shell",inline: "sysctl -w net.ipv4.ip_forward=1"
    left.vm.provision "shell" ,inline: "ip route add 10.11.30.0/24 via 10.11.12.20;true"

  end


  config.vm.define "internal" do |internal|
    
    internal.vm.box = "centos/7"
    internal.vm.hostname = "internal.local"
    internal.vm.network "private_network" , ip:"10.11.12.20", netmask:"255.255.255.0",  virtualbox__intnet: "net2"
    internal.vm.network "private_network" , ip:"10.11.30.30", netmask:"255.255.255.0",  virtualbox__intnet: "net3"

    internal.vm.provision "shell",inline: "sysctl -w net.ipv4.ip_forward=1"
    internal.vm.provision "shell",inline: "ip route add 10.9.0.0/16 via 10.11.12.10;true"

  end



end
