Vagrant.configure("2") do |config|

  config.vm.define "left" do |left|
    
    left.vm.box = "centos/7"
    left.vm.network "private_network", ip: "192.168.50.10"

    left.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbooks/do_left_side.yml"
      end

  end


  config.vm.define "right" do |right|
    
    right.vm.box = "centos/7"
    right.vm.network "private_network", ip: "192.168.50.20"

    right.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbooks/do_right_side.yml"
      end

  end

end
