- name: Check if epel repository is installed
  yum:
    name: epel-release
    state: latest
- name: Install necessary packages (for IKE strongswan is used)
  yum:
    name: [strongswan, haveged]
    state: latest
- name: Disable SELinux in configuration file
  replace:
    path: /etc/selinux/config
    regexp: SELINUX=\w*
    replace: SELINUX=disabled
- name: Disable SELinux temporarily
  shell: setenforce 0
  ignore_errors: yes
- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - haveged
    - strongswan
- name: Generate private key for VPN IPSec server
  shell: /sbin/strongswan pki --gen --type rsa --size 2048 --outform pem > {{IPSEC_PRIV_KEY_PATH}}/{{IPSEC_KEY_NAME}}
- name: Generate Certificate for VPN IPSec server to authenticate this side
  shell: /sbin/strongswan pki --pub --in {{IPSEC_PRIV_KEY_PATH}}/{{IPSEC_KEY_NAME}} --type rsa | strongswan pki --issue --lifetime 730 --cacert {{IPSEC_CERT_PATH}}/{{CA_CERT_NAME}} --cakey {{IPSEC_PRIV_KEY_PATH}}/{{CA_KEY_NAME}} --dn "{{IPSEC_DN}}" --san {{IPSEC_FQDN}} --flag serverAuth --flag ikeIntermediate --outform pem > {{IPSEC_CERT_PATH}}/{{IPSEC_CERT_NAME}}
