- hosts: all
  become: yes
  tasks:
    - name: Install EPEL-Release
      yum:
        name: epel-release
        state: latest
    - name: Install OpenVPN
      yum:
        name: openvpn
        state: latest







