---
  - hosts: all
    vars_files:
      - config/main.yaml
      - config/syslog_conf.yaml
    tasks:
      - name: Ensure rsyslog is not installed
        yum:
          name: rsyslog
          state: absent
      - name: Install more convenient syslog-ng
        yum:
          name: syslog-ng
          state: latest
      - name: Deploy configuration for syslog-ng
        template:
          src: templates/syslog-ng/02-remote-syslog.conf
          dest: /etc/syslog-ng/conf.d/02-remote-syslog.conf
      - name: Restart syslog-ng and make in autorunning
        service:
          name: syslog-ng
          state: restarted
          enabled: yes
