- hosts: servers
  become: yes
  roles:
  - role: syslog-ng
    vars:
      REMOTE_ENABLED: true
      REMOTE_SYSLOG_SERVER: 127.0.0.1
      REMOTE_SYSLOG_PORT: 50514
      SOURCE_FILES:
        audit_centos: /var/log/audit/audit.log
        nginx_default: /var/log/nginx/access.log